import {
  AppWindow,
  Battery,
  Bell,
  Bluetooth,
  Calendar,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Files,
  Gauge,
  Globe,
  Headphones,
  Network,
  Plus,
  Power,
  RefreshCw,
  Search,
  Settings,
  Shield,
  Sparkles,
  Sun,
  Terminal,
  Volume2,
  VolumeX,
  Wifi,
  X,
  createElement,
  type IconNode,
} from "lucide";

const icons: Record<string, IconNode> = {
  app: AppWindow,
  battery: Battery,
  bell: Bell,
  bluetooth: Bluetooth,
  browser: Globe,
  calendar: Calendar,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  close: X,
  files: Files,
  gauge: Gauge,
  headphones: Headphones,
  network: Network,
  plus: Plus,
  power: Power,
  refresh: RefreshCw,
  search: Search,
  settings: Settings,
  shield: Shield,
  sparkles: Sparkles,
  sun: Sun,
  terminal: Terminal,
  volume: Volume2,
  "volume-muted": VolumeX,
  wifi: Wifi,
};

export const icon = (name: string) =>
  createElement(icons[name] ?? AppWindow, {
    "aria-hidden": "true",
    width: 24,
    height: 24,
    "stroke-width": 1.9,
  }).outerHTML;

export const iconNode = (name: string) => icons[name] ?? AppWindow;
