import {
  Accessibility,
  Activity,
  AppWindow,
  ArrowDown,
  ArrowUp,
  Battery,
  Bell,
  BellOff,
  Bluetooth,
  Calendar,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock3,
  Files,
  Gauge,
  Globe,
  Headphones,
  Image,
  Info,
  Keyboard,
  Laptop,
  Lock,
  Menu,
  Mic,
  Minus,
  Moon,
  MousePointer2,
  Network,
  Palette,
  PanelBottom,
  Plus,
  Power,
  RefreshCw,
  RotateCcw,
  ScanSearch,
  Search,
  Settings,
  Shield,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Square,
  Sun,
  Terminal,
  Trash2,
  UserRound,
  Volume2,
  VolumeX,
  Wifi,
  X,
  createElement,
  type IconNode,
} from "lucide";

const icons: Record<string, IconNode> = {
  accessibility: Accessibility,
  activity: Activity,
  app: AppWindow,
  "arrow-down": ArrowDown,
  "arrow-up": ArrowUp,
  battery: Battery,
  bell: Bell,
  "bell-off": BellOff,
  bluetooth: Bluetooth,
  browser: Globe,
  calendar: Calendar,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  clock: Clock3,
  close: X,
  files: Files,
  gauge: Gauge,
  headphones: Headphones,
  image: Image,
  info: Info,
  keyboard: Keyboard,
  laptop: Laptop,
  lock: Lock,
  menu: Menu,
  mic: Mic,
  minimize: Minus,
  moon: Moon,
  mouse: MousePointer2,
  network: Network,
  palette: Palette,
  panel: PanelBottom,
  plus: Plus,
  power: Power,
  refresh: RefreshCw,
  reboot: RotateCcw,
  "scan-search": ScanSearch,
  search: Search,
  settings: Settings,
  shield: Shield,
  "shield-check": ShieldCheck,
  sliders: SlidersHorizontal,
  sparkles: Sparkles,
  maximize: Square,
  sun: Sun,
  terminal: Terminal,
  trash: Trash2,
  user: UserRound,
  volume: Volume2,
  "volume-muted": VolumeX,
  wifi: Wifi,
};

export const icon = (name: string) =>
  createElement(icons[name] ?? AppWindow, {
    "aria-hidden": "true",
    width: 24,
    height: 24,
    "stroke-width": 1.9,
  }).outerHTML;

export const iconNode = (name: string) => icons[name] ?? AppWindow;
